const CONFIG = {
    AUTH_SERVICE_URL: process.env.NEXT_PUBLIC_AUTH_SERVICE_URL || '',
    ATTENDANCE_SERVICE_URL: process.env.NEXT_PUBLIC_ATTENDANCE_SERVICE_URL || '',
    FILE_SERVICE_URL: process.env.NEXT_PUBLIC_FILE_SERVICE_URL || '',
    EMPLOYEE_SERVICE_URL: process.env.NEXT_PUBLIC_EMPLOYEE_SERVICE_URL || '',
};

export default CONFIG;
