# Build stage
FROM node:18 as builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Production stage
FROM node:18

WORKDIR /app

COPY --from=builder /app ./

EXPOSE 4000

ENV PORT 4000

CMD ["npm", "run", "start"]
